# projects/personal-website/tests/test_html_structure.py
import os
import re
import pytest
from bs4 import BeautifulSoup

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

EXPECTED_HTML_FILES = [
    "index.html",
    "articles/index.html",
    "articles/multimodal-rag-image-extraction.html",
    "articles/rag-system-evaluation-and-metrics.html",
    "articles/hybrid-retrieval-rrf-and-fusion.html",
    "articles/agentic-rag-routing-and-crag.html"
]

@pytest.mark.parametrize("rel_path", EXPECTED_HTML_FILES)
def test_html_files_exist_and_valid(rel_path):
    full_path = os.path.join(PROJECT_ROOT, rel_path)
    assert os.path.exists(full_path), f"File {rel_path} does not exist!"
    
    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    assert len(content) > 500, f"File {rel_path} is unexpectedly small!"
    soup = BeautifulSoup(content, "html.parser")
    
    # 1. Essential SEO and metadata checks
    assert soup.find("title") is not None, f"Missing <title> in {rel_path}"
    assert soup.find("meta", {"name": "viewport"}) is not None, f"Missing viewport in {rel_path}"
    assert soup.find("meta", {"name": "description"}) is not None, f"Missing description in {rel_path}"
    
    # 2. Check for author branding
    assert "Prajwal Rao" in content, f"Missing Prajwal Rao branding in {rel_path}"
    
    # 3. Check for No AI attribution
    forbidden_terms = [
        "Generated by", "GitHub Copilot", "AI-generated", "ChatGPT", "Antigravity", "OpenAI language model"
    ]
    for term in forbidden_terms:
        assert term.lower() not in content.lower(), f"Forbidden AI attribution '{term}' found in {rel_path}!"

def test_relative_links_integrity():
    for rel_path in EXPECTED_HTML_FILES:
        full_path = os.path.join(PROJECT_ROOT, rel_path)
        base_dir = os.path.dirname(full_path)
        
        with open(full_path, "r", encoding="utf-8") as f:
            soup = BeautifulSoup(f.read(), "html.parser")
            
        links = soup.find_all(["a", "link", "script"])
        for tag in links:
            target = tag.get("href") or tag.get("src")
            if not target or target.startswith(("http", "https", "mailto:", "#")):
                continue
            
            # Clean anchor fragment from target
            clean_target = target.split("#")[0]
            if not clean_target:
                continue
                
            resolved_path = os.path.normpath(os.path.join(base_dir, clean_target))
            assert os.path.exists(resolved_path), f"Broken link '{target}' found in {rel_path} (resolved to {resolved_path})"

def test_interactive_rrf_elements():
    # Verify the hybrid article contains the required RRF calculator IDs
    pages_with_calculator = [
        "articles/hybrid-retrieval-rrf-and-fusion.html"
    ]
    required_ids = [
        "rrf-k-slider",
        "rrf-k-val",
        "rrf-dense-slider",
        "rrf-dense-val",
        "rrf-sparse-slider",
        "rrf-sparse-val",
        "rrf-results-body"
    ]
    
    for rel_path in pages_with_calculator:
        full_path = os.path.join(PROJECT_ROOT, rel_path)
        with open(full_path, "r", encoding="utf-8") as f:
            soup = BeautifulSoup(f.read(), "html.parser")
        
        for elem_id in required_ids:
            assert soup.find(id=elem_id) is not None, f"Missing element with id='{elem_id}' in {rel_path}"

def test_dual_tier_callouts_in_articles():
    article_files = [
        "articles/multimodal-rag-image-extraction.html",
        "articles/rag-system-evaluation-and-metrics.html",
        "articles/hybrid-retrieval-rrf-and-fusion.html",
        "articles/agentic-rag-routing-and-crag.html"
    ]
    for rel_path in article_files:
        full_path = os.path.join(PROJECT_ROOT, rel_path)
        with open(full_path, "r", encoding="utf-8") as f:
            soup = BeautifulSoup(f.read(), "html.parser")
        
        novice_callouts = soup.find_all(class_="callout-novice")
        deepdive_callouts = soup.find_all(class_="callout-deepdive")
        
        assert len(novice_callouts) >= 1, f"Article {rel_path} lacks a Novice 2-Minute Intuition callout!"
        assert len(deepdive_callouts) >= 1, f"Article {rel_path} lacks an Intermediate/Deep-Dive callout!"
